services:
  - type: worker
    name: archvc
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: starter
    autoDeploy: true
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: LOG_GROUP_ID
        sync: false
      - key: SESSION_KEY
        sync: false
      - key: MONGO_URI
        sync: false
      - key: MONGO_DB
        value: archvc
      - key: VC_WORKERS
        value: "20"
      - key: PYTHON_VERSION
        value: "3.12"
